### ISSUE TITLE
Can this be used w/ Authorization Code as the grant type

### ISSUE THREAD

**Issue by manderso7** [MyPureCloud/platform-client-sdk-python#3]
I need to get call history data using a script, and have turned to this library. However, it looks like I can use the grant types "client credentials" and "OAUTH2 SAML2 BEARER GRANT". My sources have asked me to use the authorization code grant type. Will this library work for my needs?

Thank you

**Comment by PrinceNebulon** [comment]
You can use the auth code grant with the Python SDK; the SDK just doesn't have a helper for it. You'll need to make the request to exchange the code for a token and then set the token on the SDK. 

* If you'd like, you can use the `request` method on ApiClient like the saml2 and client credentials helpers do. Otherwise, you can make the request using any method you like. https://github.com/MyPureCloud/platform-client-sdk-python/blob/master/build/PureCloudPlatformClientV2/api_client.py#L116
* Details on implementing the auth code flow: https://developer.mypurecloud.com/api/rest/authorization/use-authorization-code.html
* Example implementing the auth code flow without the SDK: https://developer.mypurecloud.com/api/tutorials/oauth-auth-code/?language=python&step=1

If you have any follow up questions, you can create a new topic on the Genesys Cloud Developer Forum: https://developer.mypurecloud.com/forum/c/platform-api/python-sdk/9.
